-- ============================================================
-- Treinamentos > Cursos — cadastro de cursos (Interno/Externo) e, para os
-- Internos, a lista de aulas de cada curso.
-- Execute este script no SQL Editor do Supabase.
-- ============================================================

-- 1) Cursos
create table if not exists public.cursos (
  id bigint generated by default as identity primary key,
  nome text not null,
  tipo text not null check (tipo in ('Interno', 'Externo')),
  carga_horaria numeric,
  descricao text,
  created_at timestamptz not null default now()
);

-- 2) Aulas de um curso Interno (não existe linha aqui para cursos Externo).
-- tipo_video: 'link' (URL externa, ex. YouTube) ou 'upload' (arquivo de vídeo
-- enviado para o Drive) — em ambos os casos url_video guarda o link final.
-- url_material_pdf é opcional (nem toda aula precisa ter material anexado).
create table if not exists public.curso_aulas (
  id bigint generated by default as identity primary key,
  id_curso bigint not null references public.cursos(id) on delete cascade,
  titulo text not null,
  tipo_video text not null check (tipo_video in ('link', 'upload')),
  url_video text,
  descricao text,
  duracao_segundos integer,
  url_material_pdf text,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_curso_aulas_id_curso on public.curso_aulas(id_curso);

-- 3) RLS — mesmo modelo usado em colaboradores/candidaturas/etc: só quem está
-- autenticado no painel (RH/Administrador, controlado pela tela de
-- Permissões de Acesso) consegue ler/escrever. Sem grant nenhum para anon —
-- esta área não tem nenhum fluxo público.
alter table public.cursos enable row level security;
alter table public.curso_aulas enable row level security;

create policy "cursos_all_authenticated" on public.cursos
for all to authenticated using (true) with check (true);

create policy "curso_aulas_all_authenticated" on public.curso_aulas
for all to authenticated using (true) with check (true);

-- 4) Libera a página "Cursos" (dentro de Treinamentos) para quem já tinha
-- acesso total (Administrador e RH) — mesmo padrão de
-- sql/permissoes-usuarios.sql. Diferente de "Cadastro de Usuário e
-- Liberação", esta página NÃO é travada direto no código: dá pra liberar
-- pra outros perfis depois só ajustando a grade em Permissões de Acesso.
insert into public.permissoes (perfil_id, pagina_id)
select id, 'trein-cursos' from public.perfis where nome in ('Administrador', 'RH')
on conflict (perfil_id, pagina_id) do nothing;
