-- ============================================================
-- Perfil Treinamento > Cursos (Em Andamento / Concluídos) — progresso do
-- colaborador em cada curso liberado (curso_liberacoes), incluindo o
-- resultado da Avaliação Final.
-- Execute este script no SQL Editor do Supabase.
-- ============================================================

-- aulas_concluidas: array de ids de curso_aulas já marcadas como concluídas,
-- ex.: [12, 13, 15].
create table if not exists public.curso_progresso (
  id bigint generated by default as identity primary key,
  id_curso bigint not null references public.cursos(id) on delete cascade,
  id_colaborador bigint not null references public.colaboradores(id_colaborador) on delete cascade,
  aulas_concluidas jsonb not null default '[]'::jsonb,
  status text not null default 'em_andamento' check (status in ('em_andamento', 'concluido')),
  resultado_avaliacao text check (resultado_avaliacao in ('Aprovado', 'Reprovado')),
  percentual_acerto numeric,
  iniciado_em timestamptz not null default now(),
  concluido_em timestamptz,
  unique (id_curso, id_colaborador)
);

create index if not exists idx_curso_progresso_colaborador on public.curso_progresso(id_colaborador);

-- RLS — mesmo modelo das demais tabelas de Cursos: liberado pra qualquer
-- usuário autenticado no painel (a própria tela só deixa o colaborador
-- logado ver/mexer no progresso dele mesmo, filtrando por currentUser.colaboradorId).
alter table public.curso_progresso enable row level security;

create policy "curso_progresso_all_authenticated" on public.curso_progresso
for all to authenticated using (true) with check (true);

-- Libera a página "Cursos" (perfil Treinamento) — id 'meus-cursos' no NAV.
insert into public.permissoes (perfil_id, pagina_id)
select id, 'meus-cursos' from public.perfis where nome = 'Treinamento'
on conflict (perfil_id, pagina_id) do nothing;
