-- ============================================================
-- Treinamentos > Cursos > Avaliação Final (só cursos Internos) — perguntas
-- objetivas (múltipla escolha) com as alternativas e a correta marcada,
-- guardadas em JSON por pergunta.
-- Execute este script no SQL Editor do Supabase.
-- ============================================================

-- alternativas: array de objetos [{ "texto": "...", "correta": true|false }, ...]
create table if not exists public.curso_avaliacao_perguntas (
  id bigint generated by default as identity primary key,
  id_curso bigint not null references public.cursos(id) on delete cascade,
  enunciado text not null,
  alternativas jsonb not null default '[]'::jsonb,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_curso_avaliacao_perguntas_id_curso on public.curso_avaliacao_perguntas(id_curso);

-- RLS — mesmo modelo das demais tabelas de Cursos: só authenticated (painel).
alter table public.curso_avaliacao_perguntas enable row level security;

create policy "curso_avaliacao_perguntas_all_authenticated" on public.curso_avaliacao_perguntas
for all to authenticated using (true) with check (true);
